name: screendigital
description: Tela da recepcao

dependencies:
  flutter:
    sdk: flutter
  firebase_core: '^0.2.4'
  firebase_database: '^1.0.1'
  firebase_auth: '^0.5.11'
  carousel_slider: "^0.0.4"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icon-512x512.jpg
     - assets/logo.jpeg
     - assets/logo_b.jpg
     - assets/chanceflurries.png
     - assets/chancerain.png
     - assets/chancesleet.png
     - assets/chancesnow.png
     - assets/chancetstorms.png
     - assets/clear.png
     - assets/cloudy.png
     - assets/flurries.png
     - assets/fog.png
     - assets/hazy.png
     - assets/mostlycloudy.png
     - assets/mostlysunny.png
     - assets/nt_chanceflurries.png
     - assets/nt_chancerain.png
     - assets/nt_chancesleet.png
     - assets/nt_chancesnow.png
     - assets/nt_chancetstorms.png
     - assets/nt_clear.png
     - assets/nt_cloudy.png
     - assets/nt_flurries.png
     - assets/nt_fog.png
     - assets/nt_hazy.png
     - assets/nt_mostlycloudy.png
     - assets/nt_mostlysunny.png
     - assets/nt_partlycloudy.png
     - assets/nt_rain.png
     - assets/nt_sleet.png
     - assets/nt_snow.png
     - assets/nt_sunny.png
     - assets/nt_tstorms.png
     - assets/nt_unknown.png
     - assets/partlycloudy.png
     - assets/partlysunny.png
     - assets/rain.png
     - assets/sleet.png
     - assets/snow.png
     - assets/sunny.png
     - assets/tstorms.png
     - assets/unknown.png
     - assets/wundergroundlogo.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
